services:
  dkr-web:
    build:
      context: .                  # Root context, since Dockerfile is now in project root
      dockerfile: Dockerfile     # Dockerfile is now directly in root
    ports:
      - "52595:443"
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings__DefaultConnection=Server=DESKTOP-QV6CK5K\\SQLEXPRESS;Database=DKRSystemDb;Trusted_Connection=True;TrustServerCertificate=True"
      - DeploymentMode=OnPremise
    depends_on:
      - dkr-db
    networks:
      - dkr-network
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs

  dkr-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - dkr-db-data:/var/opt/mssql
    networks:
      - dkr-network

volumes:
  dkr-db-data:

networks:
  dkr-network:
    driver: bridge
