version: '3.8'

services:
  dkr-web:
    build:
      context: ./src                     # Root of source files
      dockerfile: Dockerfile             # Path to Dockerfile relative to context
    ports:
      - "52595:443"
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sg1-wsq2.my-hosting-panel.com;Database=hindwave_DKR;User Id=dkr;Password=DKR@123!@#;
      - DeploymentMode=OnPremise
    depends_on:
      - dkr-db
    networks:
      - dkr-network
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs

  dkr-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - dkr-db-data:/var/opt/mssql
    networks:
      - dkr-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dkr-db-data:

networks:
  dkr-network:
    driver: bridge
